apiVersion: 1

datasources:
- name: VictoriaMetrics
  type: prometheus
  uid: victoria-metrics-uid
  access: proxy
  url: http://victoria-metrics:8428
  isDefault: true
  jsonData:
    timeInterval: "1s"
    httpMethod: POST
